### ISSUE TITLE
Update spiffe-vault helm chart to run docker daemon on HTTPS

### ISSUE THREAD

**Issue by marcofranssen** [philips-labs/spiffe-vault#8]
Remove

```yaml
          env:
            - name: DOCKER_TLS_CERTDIR
              value: ''
```

Change

From

```yaml
          env:
            - name: DOCKER_HOST
              value: tcp://localhost:2375
```

To

```
          env:
            - name: DOCKER_HOST
              value: tcp://localhost:2376
```

Figure out how to connect the docker cli on https level so we don't get the error about trying to reach on http.

Found this docker-compose example. Seems we need to share the certs folder between the client and daemon.

```yaml
version: '3'
services:
  docker:
    # Starts a Docker daemon at the DNS name "docker"
    # Note:
    #  * This must be called "docker" to line up with the default
    #    TLS certificate name
    #  * DOCKER_TLS_CERTDIR defaults to "/certs
    image: docker:dind
    privileged: yes
    volumes:
      - certs:/certs/client
  docker-client:
    # Provides a Docker client container, including the client
    # certs generated by the docker:dind container, above.
    # Notes:
    #  * The name of this container doesn't matter
    #  * The DOCKER_CERT_PATH defaults to /certs/client, the
    #    same path where the docker:dind image generates the
    #    client certificate (and that we've mounted inside this
    #    container).
    # You can execute a shell inside this container by running:
    #   docker-compose exec docker-client sh
    image: docker
    command: sh -c 'while [ 1 ]; do sleep 1000; done'
    environment:
      DOCKER_HOST: tcp://docker:2376
    volumes:
      - certs:/certs/client
volumes:
  certs:
```
